from enum import Enum

class CancellationReason(Enum):
    CONSUMER_REQUEST = 'CONSUMER_REQUEST'
    UNDELIVERABLE = 'UNDELIVERABLE'
    DUPLICATE = 'DUPLICATE'
    FRAUDULENT = 'FRAUDULENT'
    ORDER_SHIPPED_IN_FULL = 'ORDER_SHIPPED_IN_FULL'
    AUTOMATED_SHIPMENT_FAILED = 'AUTOMATED_SHIPMENT_FAILED'
