from enum import Enum


class PaymentType(str, Enum):
    SALE = "SALE"
    RESERVATION = "RESERVATION"
    CAPTURE = "CAPTURE"
    REFUND = "REFUND"
    REVERSAL = "REVERSAL"
    CHARGEBACK = "CHARGEBACK"
    CHARGEBACK_REVERSAL = "CHARGEBACK_REVERSAL"
    CREDIT_NOTE = "CREDIT_NOTE"
    DEBIT_NOTE = "DEBIT_NOTE"
